# Generated by Django 5.2 on 2025-05-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_historicalevents_options_and_more'),
        ('accounts', 'create_missing_profiles'),
    ]

    operations = [
    ]
