# Generated by Django 5.2 on 2025-05-04 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20250504_1327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
