# Generated by Django 5.2 on 2025-05-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_eventupvote_alter_historicalevents_upvotes'),
    ]

    operations = [
    ]
