# Generated by Django 5.2 on 2025-05-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20250504_1335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='accounts_profile',
        ),
    ]
