# Generated by Django 5.2 on 2025-05-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_reset_models'),
        ('accounts', '0008_alter_profile_table'),
    ]

    operations = [
    ]
