# Generated by Django 5.2 on 2025-05-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_0007_reset_models_0008_alter_profile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalevents',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='historicalevents',
            name='upvote_count',
        ),
        migrations.DeleteModel(
            name='EventUpvote',
        ),
    ]
