# Generated by Django 5.2 on 2025-05-05 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEventUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], db_column='vote_type', default='upvote', max_length=10)),
                ('historicalevent', models.ForeignKey(db_column='accounts_historicalevents_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='accounts.historicalevents')),
                ('user', models.ForeignKey(db_column='accounts_profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_historicalevents_upvotes',
                'unique_together': {('historicalevent', 'user')},
            },
        ),
    ]
