# Generated by Django 5.2 on 2025-05-06 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_historicaleventupvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaleventupvote',
            name='user',
            field=models.ForeignKey(db_column='accounts_profile', on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
